### ISSUE TITLE
Add Kotlin Compose Multiplatform

### ISSUE THREAD

**Issue by androidovshchik** [sudhakar3697/electron-alternatives#24]
I think it would be nice to add the first Kotlin language framework.
This framework supports all desktop OS via JVM, web and android.
[About project](https://www.jetbrains.com/lp/compose-mpp/)

**Comment by sudhakar3697** [comment]
Thank you @androidovshchik . Could you please raise a PR adding those?.

**Comment by androidovshchik** [comment]
#25
