### ISSUE TITLE
change description in repo

### ISSUE THREAD

**Issue by degaur** [sudhakar3697/electron-alternatives#41]
> Few Cross platform desktop GUI App development options are listed here

*vs*

> A curated list of awesome [Electron](https://electronjs.org/) alternatives.

or 

*vs*

***img-before***

![image](https://github.com/sudhakar3697/electron-alternatives/assets/119423239/ce195c66-66dc-4bfa-b278-3d316bfa5619)

*vs*

***img-after***

![image](https://github.com/sudhakar3697/electron-alternatives/assets/119423239/ff180a87-bb3e-4909-9423-3cd497b3588f)

**Comment by sudhakar3697** [comment]
Done. Thank you.
