### ISSUE TITLE
Please consider adding Godot

### ISSUE THREAD

**Issue by ithgub** [sudhakar3697/electron-alternatives#7]
https://godotengine.org/  
https://github.com/godotengine  

---

my free citing from  
https://medium.com/swlh/what-makes-godot-engine-great-for-advance-gui-applications-b1cfb941df3b  
  
[Godot Editor](https://docs.godotengine.org/en/stable/getting_started/step_by_step/intro_to_the_editor_interface.html) has an exceptionally sophisticated system for making graphical user interfaces, made with the Godot Game Engine itself. They are really [eating their own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)
* It is Tiny - all of Godot with Engine end Editor is a mere 31.1 MB download. One click installation and the editor launches instantly. When I unpack and install it is still just around 70 MB.
* It is a Blast to Use
* Sane UI Component Selection
* Superior Customization of UI Components
* Editing and Modifying Running Applications - you can run your application and modify its GUI layout and the code of attached scripts while it is running and those changes get immediately reflected in the running application.  
  
Drawbacks:
* accessibility - it will not work with screen readers. This might change, there is some discussion on github
* non-native look

---

A guide to making an RSS Reader in Godot:  
https://andreww.xyz/tutorials/2019-02-25-creating-an-rss-reader-in-godot-part-1/  
https://andreww.xyz/tutorials/2019-03-05-creating-an-rss-reader-in-godot-part-2/  
https://andreww.xyz/tutorials/2019-03-17-creating-an-rss-reader-in-godot-part-3/  
an alpha release for windows and mac:  
https://github.com/triptych/godot_reader/releases

---

my free citing from  
https://godotengine.org/features  
  
The editor runs on 32-bit and 64-bit Windows, macOS, Linux, and *BSD.  
Export to:
* desktop platforms: Windows, macOS, Linux, UWP, and *BSD.
* mobile platforms: iOS and Android.
* consoles: Nintendo Switch, PlayStation 4, Xbox One via third-party providers.
* the web using HTML5 and WebAssembly.  
  
One-click deploy & export to most platforms. Easily create custom builds as well.  
  
Augmented and Virtual Reality support  

---

my free citing from  
https://docs.godotengine.org/en/stable/about/list_of_features.html#scripting
https://docs.godotengine.org/en/stable/about/list_of_features.html#miscellaneous
https://godotengine.org/article/godot-getting-more-languages

Languages to work with:
* GDScript - the main supported language
* C#
* VisualScript  

GDNative - link to native libraries
* C
* C++
* D, Kotlin, Python, Nim, and Rust bindings provided by the community

Engine and editor written in C++03
Godot 4.0 will be written in C++17

---

my free citing from  
https://godotengine.org/article/godot-editor-running-web-browser  
  
run the Godot Editor in browsers (early stage prototype, requires a recent Chromium-based browser or Firefox Nightly)  
https://godotengine.org/online/godot.tools.html

**Comment by sudhakar3697** [comment]
@ithgub  Added. Thank you :).
