### ISSUE TITLE
category or type of technology?

### ISSUE THREAD

**Issue by ghost** [sudhakar3697/electron-alternatives#94]

**Comment by sudhakar3697** [comment]
> Hi.
> 
> Would it be interesting to divide electron alternatives by category or type of technology, instead of the programming language?
> 
> * Web view x web render?
> * mwvr(minimal web view render) x web page application (hta, pwa, mpa, spa)?
> * gui(graphical user interface) x tui(terminal user interface)?
> * ui\ux\design\prototypes(7.css, xp.css ...) x browser engines(gecko, webkit, khtml, edgeHtml)?
> * mwv(minimal web view) x frameworks(react, vuejs ...)?
> 
> Is it interesting to divide the sections by technology instead of programming language?
> 
> ```mermaid
> gantt
>     title Electron Alternatives 
>     dateFormat  X
>     axisFormat %s
> 
>     section GUI Python
>     111900  : 0, 111900   
>     section Gui Prolog 
>     40100 : 0, 40100 
>     section Tauri
>     77100 : 0, 77100
>     section NodeGUI
>     8700  : 0, 8700
>     section Neutralino
>     7200  : 0, 7200
>     section Wails
>     22100 : 0, 22100
>     section Flutter
>     161700: 0, 161700
>     section .Net MAUI
>     21500: 0, 21500
> ```

Yeah. It's interesting. I feel having both views would be nice. Thank you.
